services:
    frontend:
        build: frontend
        ports:
            - 3000:3000
    api:
        build: server
        ports:
            - 8000:8000
        volumes:
            - ./server:/opt/server
    worker:
        build: backend-worker
        volumes:
            - ./backend-worker:/opt/worker
